#!/bin/bash
cd "$(dirname "$0")";

source base.cfg

serverdir=$basedir"server/"
moddir=$serverdir"mods/"
smthchanged=false
multimcversion=`cat multimc.version`
multimcarchivename=enderiotest_multimc_rev$multimcversion
multimcmodsdir=$basedir"multimc/.minecraft/mods/"

echo $multimcmodsdir
echo $multimcarchivname
echo $(expr $multimcversion + 1)


echo "Parse API data to find file name of latest EnderCore build"
enderCoreFile=$(curl -s http://ci.tterrag.com/job/EnderCore-1.11/lastSuccessfulBuild/api/json | jq -r '.artifacts[3].fileName')
enderCoreURL="http://ci.tterrag.com/job/EnderCore-1.11/lastSuccessfulBuild/artifact/build/libs/$enderCoreFile"
echo "Check if EnderCore is up to date"
if [ -e $enderCoreFile ]; then
  # If it is, do nothing
  echo "EnderCore is up to date!"
else
  # Otherwise, delete and redownload

  smthchanged=true
  # Remove old bot jar
  echo "Deleting old EnderCore jar"
  rm -f EnderCore-*
  # Download new bot jar
  echo "Downloading new file: $enderCoreFile"
  wget $enderCoreURL
  echo "deleting mod "$moddir"EnderCore-*"
  echo "deleting multimcmod" $multimcmodsdir"EnderCore-*"
  rm -f "$moddir"EnderCore-*
  rm -f "$multimcmodsdir"EnderCore-*
  echo "copy mod"
  cp $enderCoreFile $moddir
  cp $enderCoreFile $multimcmodsdir
fi



echo "Parse API data to find file name of latest EnderIO build"
enderioFile=$(curl -s http://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/lastSuccessfulBuild/api/json | jq -r '.artifacts[1].fileName')
enderioURL=http://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/lastSuccessfulBuild/artifact/build/libs/$enderioFile

echo "Check if EnderIO is up to date"
if [ -e $enderioFile ]; then
  # If it is, do nothing
  echo "EnderIO up to date!"
else
  # Otherwise, delete and redownload

  smthchanged=true
  # Remove old bot jar
  echo "Deleting old EnderIO jar"
  rm -f EnderIO-*

  # Download new bot jar
  echo "Downloading new file: $filename"
  wget $enderioURL
  echo "deleting mod "$moddir"EnderIO-*"
  rm -f "$moddir"EnderIO-*
  rm -f "$multimcmodsdir"EnderIO-*
  echo "copy mod"
  cp $enderioFile $moddir
  cp $enderioFile $multimcmodsdir
fi



# Start new bot instance
echo "Starting screen"

if [ "$smthchanged" = true ] ; then
    echo 'Be careful not to fall off!'
fi

if ! screen -list | grep -q "mcscreen"; then
  echo "No current Minecraft instance found"
  screen -dmS mcscreen
fi

if [ "$smthchanged" = true ] ; then

  echo $(expr $multimcversion + 1) > multimc.version

  zip -r $multimcarchivename multimc
  rm -f "$webroot"*.zip
  mv "$multimcarchivename".zip $webroot

  echo "Terminating current Minecraft instance"
  screen -S mcscreen -p 0 -X stuff "say installed new Ender-IO/Core version, restarting server in 30 seconds ^M"

  sleep 10 &
  wait %1
  screen -S mcscreen -p 0 -X stuff "say 20 seconds remaining ^M"


  sleep 10 &

screen -S mcscreen -p 0 -X stuff "say 10 seconds remaining ^M"

	COUNTER=9
         while [  $COUNTER -lt 10 ]; do
	      screen -S mcscreen -p 0 -X stuff "say ... $COUNTER ^M"
	      sleep 1 &
	      wait %1

             let COUNTER=COUNTER-1
         done

  screen -S mcscreen -p 0 -X stuff "stop^M"
  sleep 10 &
  wait %1
  screen -S mcscreen -p 0 -X stuff 'cd '$serverdir'^M'
  screen -S mcscreen -p 0 -X stuff 'java -jar forge-1.11.2-13.20.1.2588-universal.jar nogui ^M'

  mufile="$multimcarchivename".zip
  awk  '{gsub(/\$mufile/,"'$mufile'");gsub(/\$enderioURL/,"'$enderioURL'");gsub(/\$enderioFile/,"'$enderioFile'");gsub(/\$enderCoreURL/,"'$enderCoreURL'");gsub(/\$enderCoreFile/,"'$enderCoreFile'")}1' $basedir'html/index.php' > $webroot'index.php'
fi

